/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("empbioSetListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheempbioSetListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheempbioSetListGenerated.onFilterBar().iCheckFilterField("employeeId");
            Then.onTheempbioSetListGenerated.onFilterBar().iCheckFilterField("phoneNumber");
            Then.onTheempbioSetListGenerated.onFilterBar().iCheckFilterField("joinDate");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheempbioSetListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheempbioSetListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheempbioSetListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheempbioSetListGenerated.onTable().iCheckColumns(undefined, {"employeeId":{"header":"employeeId"},"firstName":{"header":"firstName"},"lastName":{"header":"lastName"},"email":{"header":"email"},"phoneNumber":{"header":"phoneNumber"},"joinDate":{"header":"joinDate"},"jobId":{"header":"jobId"},"salary":{"header":"salary"},"managerId":{"header":"managerId"},"departmentId":{"header":"departmentId"},"maritalStatus":{"header":"maritalStatus"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheempbioSetListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheempbioSetListGenerated.onTable().iCheckRows();

            When.onTheempbioSetListGenerated.onTable().iPressRow(0);
            Then.onTheempbioSetObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});